---
- name: Download software
  include_tasks: download-software.yml

- name: Setup Nginx on Windows host
  include_tasks: setup-nginx.yml

#- name: Install HTTPS on host
#  include_tasks: install-https.yml