- name: Create temporary directory on remote host
  win_file:
    path: "{{nginx_temp}}"
    state: directory

- name: Copy Nginx zip file to remote host
  win_copy:
    src: "{{temp_files}}/nginx-{{nginx_version}}.zip"
    dest: "{{nginx_temp}}\\nginx-{{nginx_version}}.zip"

- name: Unzip Nginx on remote host
  win_unzip:
    src: "{{ nginx_temp }}\\nginx-{{ nginx_version }}.zip"
    dest: "{{ nginx_temp }}\\"

- name: Stop the Nginx service
  win_service:
    name: "{{ nginx_service }}"
    start_mode: disabled
    state: stopped
  ignore_errors: yes

- name: Delete the Nginx service
  win_shell: "sc.exe delete {{ nginx_service }}"
  args:
    executable: cmd
  ignore_errors: yes

- name: Check if Nginx directory already exists
  win_stat:
    path: "{{ nginx_home }}"
  register: nginx_dir

- name: Backup old Nginx Home
  win_copy:
    src: "{{ nginx_home }}"
    dest: "{{ nginx_home }}_backup_{{ ansible_date_time.iso8601_basic_short }}"
    recurse: yes
    remote_src: yes
  when: nginx_dir.stat.exists


- name: Delete old Nginx Home After Backup
  win_file:
    path: "{{ nginx_home }}"
    state: absent
  when: nginx_dir.stat.exists

- name: Copy Nginx files to installation directory
  win_copy:
    src: "{{ nginx_temp }}\\nginx-{{ nginx_version }}\\"
    dest: "{{ nginx_home }}"
    recurse: yes
    remote_src: yes

- name: Delete Temp Directory
  win_file:
    path: "{{ nginx_temp }}"
    state: absent

- name: Copy WinSW to remote host
  win_copy:
    src: "{{temp_files}}/WinSW-x64.exe"
    dest: "{{nginx_home}}\\nginx-service.exe"

- name: Copy nginx-service.xml to remote host
  win_template:
    src: nginx-service.xml
    dest: "{{nginx_home}}\\nginx-service.xml"

- name: Install Nginx service
  win_command: "{{nginx_home}}\\nginx-service.exe install"
  args:
    chdir: "{{nginx_home}}"

- name: Install HTTPS after Nginx setup
  set_fact:
    install_https: true
