- name: Create firewall rule to allow inbound traffic on port 443
  win_firewall_rule:
    name: "Allow Inbound HTTPS"
    localport: 443
    action: allow
    direction: in
    protocol: TCP
    enabled: yes