---
# tasks file for roles/install_nginx_windows

- name: Download Nginx to local machine
  get_url:
    url: "https://nginx.org/download/nginx-{{nginx_version}}.zip"
    dest: "{{temp_files}}/nginx-{{nginx_version}}.zip"

- name: Download Nginx to local machine
  get_url:
    url: "https://github.com/winsw/winsw/releases/download/v{{winsw_version}}/WinSW-x64.exe"
    dest: "{{temp_files}}/WinSW-x64.exe"


- name: Create temporary directory on remote host
  win_file:
    path: "{{nginx_temp}}"
    state: directory

- name: Copy Nginx zip file to remote host
  copy:
    src: "{{temp_files}}/nginx-{{nginx_version}}.zip"
    dest: "{{nginx_temp}}\nginx-{{nginx_version}}.zip"

- name: Unzip Nginx on remote host
  win_unzip:
    src: "{{nginx_temp}}\nginx-{{nginx_version}}.zip"
    dest: "{{nginx_temp}}"
    creates: "{{nginx_temp}}\nginx-{{nginx_version}}"

- name: Create Nginx directory on remote host
  win_file:
    path: "{{nginx_home}}"
    state: directory

- name: Copy Nginx files to installation directory
  win_copy:
    src: "{{nginx_temp}}\nginx-{{nginx_version}}"
    dest: "{{nginx_home}}"
    recurse: yes

- name: Copy WinSW to remote host
  win_copy:
    src: "{{temp_files}}/WinSW-x64.exe"
    dest: "{{nginx_home}}\\nginx-service.exe"

- name: Copy nginx-service.xml to remote host
  win_copy:
    src: files/nginx-service.xml
    dest: "{{nginx_home}}\\nginx-service.xml"

- name: Install Nginx service
  win_command: "{{nginx_home}}\\nginx-service.exe install"
  args:
    chdir: "{{nginx_home}}"

- name: Start Nginx service
  win_service:
    name: "{{nginx_service}}"
    start_mode: auto
    state: started