- name: Create temporary directory on remote host
  win_file:
    path: "{{nginx_temp}}"
    state: directory

- name: Copy Nginx zip file to remote host
  win_copy:
    src: "{{temp_files}}/nginx-{{nginx_version}}.zip"
    dest: "{{nginx_temp}}\\nginx-{{nginx_version}}.zip"

- name: Unzip Nginx on remote host and rename files
  win_unzip:
    src: "{{ nginx_temp }}\\nginx-{{ nginx_version }}.zip"
    dest: "{{ nginx_temp }}\\"

- name: Copy Nginx files to installation directory
  win_copy:
    src: "{{ nginx_temp }}\\nginx-{{ nginx_version }}\\"
    dest: "{{ nginx_home }}"
    recurse: yes
    remote_src: yes

- name: Copy Nginx files to installation directory
  win_file:
    path: "{{ nginx_temp }}"
    state: absent

- name: Copy WinSW to remote host
  win_copy:
    src: "{{temp_files}}/WinSW-x64.exe"
    dest: "{{nginx_home}}\\nginx-service.exe"

- name: Copy nginx-service.xml to remote host
  win_copy:
    src: nginx-service.xml
    dest: "{{nginx_home}}\\nginx-service.xml"

- name: Install Nginx service
  win_command: "{{nginx_home}}\\nginx-service.exe install"
  args:
    chdir: "{{nginx_home}}"

- name: Start Nginx service
  win_service:
    name: "{{nginx_service}}"
    start_mode: auto
    state: started
