temp_files: "{{ playbook_dir }}/../temp"
servers_keys_path: "{{ playbook_dir }}/../inventories/host_vars/{{ ansible_host }}"
server_name: "{{ ansible_host }}"

nginx_version: 1.25.0
winsw_version: 2.12.0

root_dir: "C:\\"
nginx_home: "C:\\nginx"
nginx_temp: "C:\\nginx_temp"
ssl_dir: "{{nginx_home}}\\ssl"

nginx_service: "nginx"
