# tasks/main.yml

- name: Create server keys directory
  ansible.builtin.file:
    path: "{{servers_keys_path}}"
    state: directory

- name: Generate RSA private key for Server
  community.crypto.openssl_privatekey:
    path: "{{servers_keys_path}}/server.key"
    size: "{{ key_size }}"
    type: "{{ key_type }}"

- name: Create a server certificate request
  community.crypto.openssl_csr:
    path: "{{servers_keys_path}}/server.csr"
    privatekey_path: "{{servers_keys_path}}/server.key"
    common_name: '{{server_name}}'
    country_name: '{{country}}'
    organization_name: '{{organization}}'
    state_or_province_name: "{{state}}"
    email_address: "{{email}}"

- name: Sign the server certificate with Root CA
  community.crypto.x509_certificate:
    path: "{{ servers_keys_path }}/server.crt"
    privatekey_content: "{{root_keys_path}}/rootCA.key"
    csr_path: "{{ servers_keys_path }}/server.csr"
    ownca_path: "{{ root_keys_path }}/rootCA.pem"
    provider: ownca
    ownca_not_after: "+{{days}}d"
    ownca_privatekey_path: "{{root_keys_path}}/rootCA.key"