    - name: Send HTTP request to nginx
      uri:
        url: "https://{{ server_name }}/"
        method: GET
        validate_certs: no
        return_content: yes
      register: nginx_response

    - name: Check if nginx welcome message is present
      assert:
        that:
          - "'Welcome to nginx!' in nginx_response.content"
        fail_msg: "Nginx welcome page not found!"
        success_msg: "Nginx welcome page found!"
