- name: Generate certificates
  hosts: localhost
  tasks:
    - name: Generate CA root certificate
      include_tasks: generate-ca-root-cert.yml

    - name: Generate Server certificate
      include_tasks: generate-server-cert.yml

- name: Install Nginx on remote Windows server
  hosts: nginx_windows
  tasks:
    - name: Install Nginx
      include_tasks: install-nginx-windows.yml

- name: Install and Check certificates
  hosts: localhost
  tasks:
    - name: Install CA root cert on localhost
      include_tasks: install-ca-root-cert.yml

    - name: Check Result
      include_tasks: check-web-server.yml