---
# tasks file for generate_ca_root_sert

- name: Generate RSA private key
  delegate_to: localhost
  community.crypto.openssl_privatekey:
    path: "{{root_keys_path}}/rootCA.key"
    size: "{{key_size}}"
    type: "{{key_type}}"
    return_content: true
  register: new_private_key

- name: Create a root certificate request
  delegate_to: localhost
  community.crypto.openssl_csr:
    path: "{{root_keys_path}}/rootCA.csr"
    privatekey_path: "{{root_keys_path}}/rootCA.key"
    common_name: 'Root CA'
    country_name: '{{country}}'
    organization_name: '{{organization}}'
    state_or_province_name: '{{state}}'
    email_address: '{{email}}'

- name: Generate self-signed root certificate
  delegate_to: localhost
  community.crypto.x509_certificate:
    path: "{{root_keys_path}}/rootCA.pem"
    privatekey_path: "{{root_keys_path}}/rootCA.key"
    csr_path: "{{root_keys_path}}/rootCA.csr"
    provider: selfsigned
    selfsigned_notAfter: "+{{ days }}d"
